### PR TITLE
The "infernal" PR: parameter copy/paste

### PR DESCRIPTION
**Pull request by schmamps**
I call this branch "infernal" because it unfortunately contains some `black` reformatting I don't want to put back, but also because it *infers* the input parameters:

* if you copy the clip on your timeline, you can use paste to set the correct frame rate and/or duration
* if you copy the transformation keyframe, you can paste its parameters to the start and end rectangles

### CODE REVIEW

**Comment by chocolateimage** [comment]
I can't try this one out because you deleted the branch you made.

**Comment by chocolateimage** [comment]
nvm, i still downloaded it

**Comment by schmamps** [comment]
Sorry about that, I'm bad at git. 

Apparently I merged this into the master branch on my fork. After that I couldn't figure out how to rewind to yours and just fix #3

**Comment by chocolateimage** [comment]
ok, but i can't merge this PR. and i already did the issues you made

**Pull request closed without merging**
